spring.application.name=app
# 1. URL de conexión (reemplaza 'nombre_base_datos' por el tuyo)
spring.datasource.url=jdbc:mysql://localhost:3306/semillas_esperanza?serverTimezone=UTC

# 2. Credenciales de acceso a tu MySQL
spring.datasource.username=root
spring.datasource.password=root

# 3. Driver oficial de MySQL para Java
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Controla qué hace Hibernate con las tablas al iniciar la app (update solo actualiza los cambios)
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Spring Boot las consultas SQL reales que se están ejecutando
spring.jpa.show-sql=true

# Formatea el código SQL de la consola para que sea fácil de leer
spring.jpa.properties.hibernate.format_sql=true